classDiagram
direction LR

class Catalogo1 {
  +int IdCatalogo1
  +string Nombre
  +bool Activo
}

class Catalogo2 {
  +int IdCatalogo2
  +string Nombre
  +bool Activo
}

class Relacion {
  +int IdRelacion
  +int IdCatalogo1_FK
  +int IdCatalogo2_FK
  +date Fecha
  +string Estado
}

class Extra {
  +int IdExtra
  +string Nombre
  +string Correo
  +bool Activo
}

Catalogo1 "1" --> "0..*" Relacion : FK
Catalogo2 "1" --> "0..*" Relacion : FK
Extra "1" --> "0..*" Catalogo2 : participa
